name: islami_app
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.1.4+2

environment:
  sdk: ^3.7.0

dependencies:
  audio_service: ^0.18.18
  audioplayers: ^6.3.0
  cupertino_icons: ^1.0.8
  dartz: ^0.10.1
  dio: ^5.8.0+1
  easy_container: ^1.0.5+1
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.0
  flutter_qiblah: ^3.1.0+1
  flutter_screenutil: ^5.9.3
  flutter_svg: ^2.2.0
  geolocator: ^13.0.4
  geocoding: ^4.0.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  json_annotation: ^4.9.0
  just_audio: ^0.10.5
  logger: ^2.5.0
  path_provider: ^2.1.5
  quran:
    path: ./quran-1.2.2
  retrofit: ^4.0.3
  rxdart: ^0.28.0
  share_plus: ^11.1.0
  shared_preferences: ^2.5.2
  string_validator: ^0.3.0
  wakelock_plus: ^1.4.0
  record: ^6.0.0
  audio_waveforms: ^1.0.5
  vibration: ^3.1.3
  flutter_audio_waveforms: ^1.2.1+8
  flutter_local_notifications: ^19.3.0
  intl: ^0.20.0
  timezone: ^0.10.1
  auto_size_text: ^3.0.0
  rename: ^3.1.0
  equatable: ^2.0.7
  get_it: ^8.0.3
  uuid: ^4.0.0
  flutter_localizations:
    sdk: flutter
  event_bus: ^2.0.1
  adhan: ^2.0.0+1
  flutter_native_splash: ^2.4.6
  permission_handler: ^12.0.1
  package_info_plus: ^9.0.0
  connectivity_plus: ^7.0.0
  url_launcher: ^6.3.2
  screenshot: ^3.0.0
  qcf_quran: ^0.0.3
  hijri: ^3.0.0
  star_menu: ^4.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.7
  flutter_lints: ^5.0.0
  json_serializable: ^6.7.1
  retrofit_generator: ^7.0.8
  hive_generator: ^2.0.1

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/json/
    - assets/json/Azkar/
    - assets/images/
  
  # example:
  fonts:
    - family: arsura
      fonts:
        - asset: assets\fonts\arsura.ttf
    
    - family: uthmanic
      fonts:
        - asset: assets\fonts\QCF2BSMLfonts\UthmanTN1 Ver10.otf

    
  #       - asset: fonts/Schylerp1.woff
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/Trp1.woff
  #       - asset: fonts/TrajanPp1.woff
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
